import type {
  Account,
  Transaction,
  TransactionSourceType,
} from '../types/models'
import { createRepository } from './createRepository'
import { getDB } from '../db/database'

const accounts = createRepository('accounts')
const transactions = createRepository('transactions')

export const accountRepository = {
  ...accounts,

  async listBySpace(spaceId: string): Promise<Account[]> {
    return accounts.getAllByIndex('by-spaceId', spaceId)
  },
}

export const transactionRepository = {
  ...transactions,

  async listBySpace(spaceId: string): Promise<Transaction[]> {
    return transactions.getAllByIndex('by-spaceId', spaceId)
  },

  /** Transactions in a space whose `occurredAt` falls within `[fromIso, toIso]`. */
  async listBySpaceInRange(
    spaceId: string,
    fromIso: string,
    toIso: string,
  ): Promise<Transaction[]> {
    const range = IDBKeyRange.bound(
      [spaceId, fromIso],
      [spaceId, toIso],
    )
    return transactions.getAllByIndex('by-space-occurredAt', range)
  },

  /**
   * The most recent transactions in a space, newest first, walked with a
   * reverse cursor over `by-space-occurredAt` so a large history costs only
   * `limit` deserializations plus whatever soft-deleted / filtered rows are
   * skipped along the way (Roadmap Phase 26).
   */
  async listRecent(
    spaceId: string,
    options: {
      limit: number
      before?: string
      type?: Transaction['type']
      accountId?: string
    },
  ): Promise<Transaction[]> {
    const db = await getDB()
    const upper = options.before ?? '￿'
    const range = IDBKeyRange.bound(
      [spaceId, ''],
      [spaceId, upper],
      false,
      options.before !== undefined,
    )

    const out: Transaction[] = []
    let cursor = await db
      .transaction('transactions')
      .store.index('by-space-occurredAt')
      .openCursor(range, 'prev')

    while (cursor && out.length < options.limit) {
      const txn = cursor.value as Transaction
      if (
        !txn.deletedAt &&
        (!options.type || txn.type === options.type) &&
        (!options.accountId ||
          txn.accountId === options.accountId ||
          txn.destinationAccountId === options.accountId)
      ) {
        out.push(txn)
      }
      cursor = await cursor.continue()
    }

    return out
  },

  async listByAccount(accountId: string): Promise<Transaction[]> {
    return transactions.getAllByIndex('by-accountId', accountId)
  },

  /** Find the transaction generated by a shopping item / bill payment, if any. */
  async findBySource(
    sourceType: TransactionSourceType,
    sourceId: string,
  ): Promise<Transaction | undefined> {
    return transactions.getByIndex('by-source', [sourceType, sourceId])
  },

  async listPendingSync(): Promise<Transaction[]> {
    return transactions.getAllByIndex('by-syncStatus', 'PENDING', {
      includeDeleted: true,
    })
  },
}
