import type {
  Account,
  Transaction,
  TransactionSourceType,
} from '../types/models'
import { createRepository } from './createRepository'

const accounts = createRepository('accounts')
const transactions = createRepository('transactions')

export const accountRepository = {
  ...accounts,

  async listBySpace(spaceId: string): Promise<Account[]> {
    return accounts.getAllByIndex('by-spaceId', spaceId)
  },
}

export const transactionRepository = {
  ...transactions,

  async listBySpace(spaceId: string): Promise<Transaction[]> {
    return transactions.getAllByIndex('by-spaceId', spaceId)
  },

  /** Transactions in a space whose `occurredAt` falls within `[fromIso, toIso]`. */
  async listBySpaceInRange(
    spaceId: string,
    fromIso: string,
    toIso: string,
  ): Promise<Transaction[]> {
    const range = IDBKeyRange.bound(
      [spaceId, fromIso],
      [spaceId, toIso],
    )
    return transactions.getAllByIndex('by-space-occurredAt', range)
  },

  async listByAccount(accountId: string): Promise<Transaction[]> {
    return transactions.getAllByIndex('by-accountId', accountId)
  },

  /** Find the transaction generated by a shopping item / bill payment, if any. */
  async findBySource(
    sourceType: TransactionSourceType,
    sourceId: string,
  ): Promise<Transaction | undefined> {
    return transactions.getByIndex('by-source', [sourceType, sourceId])
  },

  async listPendingSync(): Promise<Transaction[]> {
    return transactions.getAllByIndex('by-syncStatus', 'PENDING', {
      includeDeleted: true,
    })
  },
}
